### ISSUE TITLE
文法のリファクタリング

### ISSUE THREAD

**Issue by shoheiyokoyama** [Kyohei-Sakai/MyBalanceInquiry#2]
今まで指摘してきたところを意識して、主に文法のリファクタリングをしよう。

**Comment by sakatore** [comment]
どこまでの単位で一緒に直しちゃっていいですか？

前みたいに、self外すのとアクセスレベルは別で直したほうがいいのか、コンフリクトが面倒なので行単位で直していいのか。

**Comment by shoheiyokoyama** [comment]
このissueに対して一気にpr出していいよ
