### ISSUE TITLE
Dateの比較演算子

### ISSUE THREAD

**Issue by shoheiyokoyama** [Kyohei-Sakai/MyBalanceInquiry#29]
Dateの比較わかりづらいから新しくオペレータ定義してみよう
[swift_nsdate_compare](http://nsblogger.hatenablog.com/entry/2016/05/02/swift_nsdate_compare)

**Comment by sakatore** [comment]
`Date`に標準で機能ついてました。

**Comment by shoheiyokoyama** [comment]
まじ？知らなかった〜
`swift3`の恩恵や
