### ISSUE TITLE
swiftファイルの保存先を変更したい

### ISSUE THREAD

**Issue by sakatore** [Kyohei-Sakai/MyBalanceInquiry#3]
いくつかswiftファイルを作成した時、MyBalanceInquiryディレクトリの外に作ってしまったので中に入れたい。

ただ移動させるだけだと、xcodeで開けなくなるのでどうすればいいですか？

**Comment by shoheiyokoyama** [comment]
view controller modelファイル構成にする

**Comment by sakatore** [comment]
BankClass.swiftはどこに入りますか？

**Comment by shoheiyokoyama** [comment]
ぱっと見modelクラスぽい
