### ISSUE TITLE
TableViewでセルの色を指定したタイミングで変更したい

### ISSUE THREAD

**Issue by sakatore** [Kyohei-Sakai/MyBalanceInquiry#31]
`MyBankViewController`では明細一覧がTableViewで表示され、`セルの選択`→`アラート`で`BankingData`のオプション(`isIncome`)を変更できる。
`isIncome`がtrueであれば、セル設定時にbackgroundに色がつく。

アラートでオプションの変更後すぐに色が変わるようにしたいです。

**Comment by shoheiyokoyama** [comment]
まず、今の色の設定の仕方だとダメだね。
r理由はtableviewをスクロールさせればわかると思う。
tableviewのcellは使いまわしているから、indexPathのsectionとrowを指定してcellwの設定をする必要があるね。

> アラートでオプションの変更後すぐに色が変わるようにしたいです。

まず、tableViewのselectionStyleを見てみて。ここでcellをtapした時の挙動を設定できる。
それで、selectionのハイライトを解除するコードがあるから、ここもうまく使ってみて

上記のように、isIncomeの場合の色の設定ができてれば、`tableView.reloadData()`で反映されると思うよ

**Comment by sakatore** [comment]
`selectionStyle`って選択されてるセルの色を変えるだけですか？
これ変えても変化ないですね、、

`tableView.reloadData()`でいけましたね。

**Comment by shoheiyokoyama** [comment]
selectionStyleはユーザがタップした時の挙動だね
色変えるのとは違う

**Comment by sakatore** [comment]
ん〜？やっぱわかんない。
`selectionStyle`はセルをタップした時の色を設定できることしか書いてないです。
