### ISSUE TITLE
textfield周りの処理

### ISSUE THREAD

**Issue by shoheiyokoyama** [Kyohei-Sakai/MyBalanceInquiry#34]
![simulator screen shot 2016 10 24 0 55 14](https://cloud.githubusercontent.com/assets/8734755/19627564/8d8f882c-9984-11e6-9bcb-5b27c0988dc0.png)
- enterで閉じるようにしよう
- キーボードが出るときと、出ない時で画面をスクロールさせて入力箇所が見えるようにしよう。contentInsetあたりをいじればいける

**Comment by shoheiyokoyama** [comment]
![simulator screen shot 2016 10 24 0 57 08](https://cloud.githubusercontent.com/assets/8734755/19627591/0d2100c0-9985-11e6-9ff1-26b497c5dac0.png)

**Comment by shoheiyokoyama** [comment]
この画面も

**Comment by shoheiyokoyama** [comment]
あと、初期残高押した時に、キーボードが数字のやつだすようにしよう

**Comment by sakatore** [comment]
```
キーボードが出るときと、出ない時で画面をスクロールさせて入力箇所が見えるようにしよう。
contentInsetあたりをいじればいける
```

普通にViewControllerのviewの位置をずらしただけなんですけど、こんなやり方あります？

**Comment by shoheiyokoyama** [comment]
割と使われてると思うよ。scrollViewを持つview(tableViewとかcollectionView)の場合は、scrollOffset変えたりもする

**Comment by shoheiyokoyama** [comment]
frameを変えるか、contentinsetをいじるかだね俺も思いつく限りは

**Comment by sakatore** [comment]
キーボードが出てくるスピードと合わせたければアニメーション使うって感じですかね？

**Comment by shoheiyokoyama** [comment]
まあ、それでもいいね。確か、`notification.userInfo[UIKeyboardAnimationDurationUserInfoKey]`とかでキーボードの移動速度とか取れる
http://xyk.hatenablog.com/entry/2014/10/02/181047
