### ISSUE TITLE
入出金データは別ファイルから読み込む

### ISSUE THREAD

**Issue by sakatore** [Kyohei-Sakai/MyBalanceInquiry#45]
`ViewController.swift`での

```swift
// 取引を追加
        myBank1.addBanking(date: dateFormatter.date(from: "2016/08/04"), banking: .withdrawal, amount: 24000)
        myBank1.addBanking(date: dateFormatter.date(from: "2016/08/10"), banking: .payment, amount: 30000)
        myBank1.addBanking(date: dateFormatter.date(from: "2016/08/20"), banking: .withdrawal, amount: 15000)
```

は1個1個書かないで、別のファイルから読み込むようにします。

機能的には影響しないですけど、テストしやすいようにするためです。

**Comment by shoheiyokoyama** [comment]
これってテストコード？
だったらいいけどdateとかって、addしたタイミングの日時にすべきだと思うんだけど

**Comment by sakatore** [comment]
多分横山さんの思ってるテストと違う。

ただの初期値として入れるデータ。
グラフにする時にもっとデータ入れなちゃいけないから、そしたら`ViewController.swift`の中があふれちゃう。

CSVファイルとか作って入れようかなと思ってるけど、別にswiftファイルとかでコードで保持したほうがいいですか？

**Comment by shoheiyokoyama** [comment]
やったことなかったけどcsvいけるっぽい。
API想定してjsonDataでやるのが理想

http://hajihaji-lemon.com/smartphone/swift/csv/


これやってみな。本来はデータはAPI通信でやるべきなんだけど、通信する時はjsonっていうデータ形式でやりとりをするんだよね。これだったローカルにjsonもたせてできるっぽいからAPIからデータ取得した時を想定してjson扱えるとおもう
http://useandmake.hatenablog.com/entry/2015/12/11/232357

**Comment by sakatore** [comment]
csvは結構前にやってたからすぐできます。

jsonも少し触れたけど、まだちゃんとわかってないからjsonでやってみますわ。
