### ISSUE TITLE
refactoring

### ISSUE THREAD

**Issue by shoheiyokoyama** [Kyohei-Sakai/MyBalanceInquiry#52]
[GraghView.swift](https://github.com/Kyohei-Sakai/MyBalanceInquiry/blob/master/MyBalanceInquiry/Views/GraghView.swift#L208-L211)

ここはまとめていい気がする

**Comment by sakatore** [comment]
グラフのは[こっち](https://github.com/Kyohei-Sakai/GraghView/issues)でお願いします

同じ内容でissue作っときました
