### ISSUE TITLE
セルの挙動がおかしい

### ISSUE THREAD

**Issue by sakatore** [Kyohei-Sakai/MyBalanceInquiry#56]
![backtableviewbug](https://cloud.githubusercontent.com/assets/19564003/21100554/13a3c43c-c0b8-11e6-96ea-713b7fc797ee.gif)

**Comment by sakatore** [comment]
本来「入」のセルのみタップしたらアラートが出て、
「はい」を選択するとそのセルの色がreload()で変更されます。

これ自体はちゃんとできますが、スクロールしてみると他のセルの色も変わってしまっています。

どうやらその間隔はセル10こおきになってました。色がつかないはずの「出」のセルも関係なく色が付きます。

`print`使ってログとって気になった点は、、

1) 始めにこれが3回も呼ばれてました。
```swift
func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
```

2) スクロールした表示されるセルに対して、
`UITableCell`の
```swift
override func setSelected(_ selected: Bool, animated: Bool)
```
が3回呼ばれた後、

```swift
func tableView(_ tableView: UITableView, cellForRowAt  indexPath: IndexPath) -> UITableViewCell
```
が呼ばれていた。


さらに上下にスクロールしまくると、めちゃくちゃに色付きのセルが出現します。
意味が分からなすぎるのでHelp！

**Comment by shoheiyokoyama** [comment]
cellは同じものを使いまわしてるから、cellForRowAtでセルの色の設定を変えてみて

```swift
if isSelectedCell {
    cell.backgroundColor = .cyan
} else {
    cell.backgroundColor = .white
}
```
